.PHONY: build-image
build-image: build-{{.AppName}}-server

.PHONY: build-{{.AppName}}-server
build-{{.AppName}}-server:
	docker build -f build/{{.AppName}}/Dockerfile -t {{.ProjectName}}-{{.AppName}}:v1 .

.PHONY: run-{{.AppName}}
run-{{.AppName}}:
	go run cmd/{{.AppName}}/main.go run -c=config/confin.toml

.PHONY: build-{{.AppName}}
build-{{.AppName}}:
	go build -o  cmd/{{.AppName}}/{{.AppName}} -ldflags "-X github.com/coder2z/g-server/xapp.appName={{.ProjectName}}_{{.AppName}}  -X github.com/coder2z/g-server/xapp.buildAppVersion=v1.0 -X github.com/coder2z/g-server/xapp.buildHost=`hostname`" cmd/{{.AppName}}/main.go