.PHONY: build-image
build-image: build-{{.AppName}}-server

.PHONY: build-{{.AppName}}-server
build-{{.AppName}}-server:
	docker build -f build/{{.AppName}}/Dockerfile -t {{.ProjectName}}-{{.AppName}}:v1 .

.PHONY: run-{{.AppName}}
run-{{.AppName}}:
	go run cmd/{{.AppName}}/main.go run -c=config/confin.toml

.PHONY: build-{{.AppName}}
build-{{.AppName}}:
	go build -o  cmd/{{.AppName}}/{{.AppName}} cmd/{{.AppName}}/main.go