.PHONY: build-image
build-image: build-{{.ProjectName}}-server

.PHONY: build-{{.ProjectName}}-server
build-{{.ProjectName}}-server:
	docker build -f build/Dockerfile -t {{.ProjectName}}:v1 .

.PHONY: run-{{.ProjectName}}
run-{{.ProjectName}}:
	go run cmd/main.go run -c=config/config.toml

.PHONY: build-{{.ProjectName}}
build-{{.ProjectName}}:
	go build -o  cmd/{{.ProjectName}} -ldflags "-X github.com/coder2z/g-server/xapp.appName={{.ProjectName}} -X github.com/coder2z/g-server/xapp.buildAppVersion=v1.0 -X github.com/coder2z/g-server/xapp.buildHost=`hostname`" cmd/main.go